### ISSUE TITLE
真的好漂亮的网站，请问可以出一个简单的部署教程吗

### ISSUE THREAD

**Issue by zzkuner** [sun0225SUN/camlife#1]

**Comment by sun0225SUN** [comment]
等我抽出时间，后面部署很丝滑的，目标是 Vercel 一键部署 :tada:

**Comment by zzkuner** [comment]
嗯嗯嗯，感谢大佬，我刚刚尝试了一下还没成功

**Comment by zzkuner** [comment]
可以请教一下大佬网站图片的保存是怎么保存的呢

**Comment by sun0225SUN** [comment]
用的 Vercel 的 Blob ，后面可以适配更多 OSS，或者自定义链接，确实有很多功能还没完成，在计划了，不会鸽的，Trust me ❤️

**Comment by zzkuner** [comment]
期待！！！，这真的是我看到最最最好看，完成度最高的一个项目了。大佬加油~！

**Comment by zzkuner** [comment]
顺便请教一下，我不是计算机专业，但是想学一下以后自己做一些内容，您可以给大概推荐一个学习路径吗

**Comment by sun0225SUN** [comment]
完成度还不高，哈哈哈，你看下 commit log，可以发现是今年十月份抽了大概一两周时间疯狂写的，明年肯定会更完善，最近在做创业项目，确实比较忙~

**Comment by sun0225SUN** [comment]
> 顺便请教一下，我不是计算机专业，但是想学一下以后自己做一些内容，您可以给大概推荐一个学习路径吗

这个路线图还不错，可以跟着这个来，https://roadmap.sh/frontend
前端基础内容的话可以看 MDN：https://developer.mozilla.org/en-US/docs/Learn

BTW，我也不是计算机专业～

**Comment by zzkuner** [comment]
嗯呢，谢谢谢谢

**Comment by zzkuner** [comment]
> 完成度还不高，哈哈哈，你看下 commit log，可以发现是今年十月份抽了大概一两周时间疯狂写的，明年肯定会更完善，最近在做创业项目，确实比较忙~

加油大佬！

**Comment by ghost** [comment]
> 用的 Vercel 的 Blob ，后面可以适配更多 OSS，或者自定义链接，确实有很多功能还没完成，在计划了，不会鸽的，Trust me ❤️

希望可以直接引用图床链接

**Comment by sun0225SUN** [comment]
> > 用的 Vercel 的 Blob ，后面可以适配更多 OSS，或者自定义链接，确实有很多功能还没完成，在计划了，不会鸽的，Trust me ❤️
> 
> 希望可以直接引用图床链接

这个主要是为了读取 Exif 信息并存储，是会支持纯图床链接的，但是元信息比如光圈、快门、感光度就必须自己手动填或使用默认值了。

**Comment by huhexian** [comment]
> 用的 Vercel 的 Blob ，后面可以适配更多 OSS，或者自定义链接，确实有很多功能还没完成，在计划了，不会鸽的，Trust me ❤️

孙哥，年底能用上吗，你说不会鸽的。

**Comment by sun0225SUN** [comment]
这么一看，都快过去（鸽）一年了，我有罪，周末就重启（大哭）

**Comment by huhexian** [comment]
> 这么一看，都快过去（鸽）一年了，我有罪，周末就重启（大哭）

你最好说的是真的。
